media: assets/uploads         # pasta para imagens
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    filename: '{year}-{month}-{day}-{title}.md'
    fields:
      - { name: title,  label: Título, type: string, required: true }
      - { name: date,   label: Data,   type: date,   required: true }
      - { name: body,   label: Corpo,  type: rich-text }
