title: "Wendel Neves - Compartilhando conhecimento"
description: "Filho, Nerd, Católico, Esposo. Meu site pessoal onde compartilho o conhecimento que vou coletando a cada dia."
theme: minima           # tema pronto do próprio GitHub Pages
site.google_analytics: "G-6XPEEQHZFH"
locale: "pt_BR"
