---
title: De Sêneca a Paulino - Sobre a brevidade da vida - Carta I
date: 2025-08-16
---


De "A sabedoria de Sêneca" - Editora Excelsior - 2021

I. Meu caro Paulino, a maior parte da humanidade reclama da crueldade da Natureza, por nascermos para viver somente por um breve espaço de tempo e por esse período de vida que nos foi concedido se esgotar tão rapidamente, ou melhor, de modo tão apressado, que, com apenas poucas exceções, a vida chega ao fim no exato momento em que as pessoas se preparar para desfrutá-la. A massa comum e os ignorantes vulgares não são os únicos a lamentar esse infortúnio universal, como o consideram; tal reflexão arrancou lástimas até mesmo de homens notáveis. Daí vem o conhecido aforismo do maior dos médicos: "A arte é longa, mas a vida é breve." Daí surgiu a briga, tão indigna de um sábio, que Aristóteles comprou com a Natureza, por ela ter dotado os animais com tantos dias de vida que alguns vivem por dez ou quinze séculos, enquanto o homem, embora nascido para vários e grandiosos feitos, recebeu um tempo de existência muito mais curto. Não recebemos um tempo muito curto, porém, desperdiçamos a maior parte dele. **A vida é longa o bastante para realizar os projetos mais importantes; recebemos uma porção generosa, se a ordenamos da maneira certa.** Contudo, quando se esvai no luxo e no descuido, quando não é dedicada a nenhum bom propósito, somos enfim forçados a perceber que se acabou, embora nunca tivéssemos notado que se esgotava. Portanto, não recebemos uma vida curta, mas a tornamos breve; não somos pobres em dias, mas os desperdiçamos. Da mesma maneira que enormes fortunas, dignas de reis, ao caírem nas mãos de um mau administrador são logo esbanjadas, enquanto uma fortuna, mesmo que modera, se concedida a um sábio guardião, aumenta pelo uso que se faz dela, assim também, nossa vida guarda grandes oportunidades para quem sabe como aproveitá-la da melhor maneira.
